# Generated by Django 3.1.7 on 2021-05-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient_medical_history',
            name='full_name',
        ),
        migrations.AlterField(
            model_name='patient_medical_history',
            name='Age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patient_medical_history',
            name='Alchohol_Consumption',
            field=models.TextField(default='Null'),
        ),
        migrations.AlterField(
            model_name='patient_medical_history',
            name='Blood_Group',
            field=models.CharField(default='Null', max_length=5),
        ),
        migrations.AlterField(
            model_name='patient_medical_history',
            name='Current_Medications',
            field=models.TextField(default='Null'),
        ),
        migrations.AlterField(
            model_name='patient_medical_history',
            name='Drug_Allergies',
            field=models.TextField(default='Null'),
        ),
        migrations.AlterField(
            model_name='patient_medical_history',
            name='Gender',
            field=models.CharField(default='Null', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient_medical_history',
            name='Height',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patient_medical_history',
            name='Smoking_Habit',
            field=models.TextField(default='Null'),
        ),
        migrations.AlterField(
            model_name='patient_medical_history',
            name='Weight',
            field=models.IntegerField(default=0),
        ),
    ]
