# Generated by Django 3.1.7 on 2021-04-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient_medical_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_name', models.CharField(max_length=100)),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(max_length=20)),
                ('Height', models.IntegerField()),
                ('Weight', models.IntegerField()),
                ('Blood_Group', models.CharField(max_length=5)),
                ('Alchohol_Consumption', models.TextField()),
                ('Smoking_Habit', models.TextField()),
                ('Drug_Allergies', models.TextField()),
                ('Current_Medications', models.TextField()),
            ],
        ),
    ]
