# Generated by Django 3.1.7 on 2021-05-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_name', models.CharField(max_length=100)),
                ('Patient_ID', models.IntegerField()),
                ('Doctor_name', models.CharField(max_length=100)),
                ('Doctor_ID', models.IntegerField()),
                ('Prescription_ID', models.IntegerField()),
                ('Prescription_Info', models.TextField()),
                ('Additional_advice', models.TextField()),
            ],
        ),
    ]
