# Generated by Django 3.1.7 on 2021-04-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_CA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('doctor_id', models.IntegerField(unique=True)),
                ('department', models.TextField()),
                ('education', models.TextField()),
                ('specialization', models.TextField()),
                ('work_experience', models.TextField()),
                ('doc_overview', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
