# Generated by Django 3.1.7 on 2021-04-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0002_auto_20210409_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_ca',
            name='department',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor_ca',
            name='education',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='doctor_ca',
            name='specialization',
            field=models.CharField(max_length=100),
        ),
    ]
