# Generated by Django 3.1.7 on 2021-05-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0003_auto_20210416_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_latest_diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_name', models.CharField(max_length=100)),
                ('Doctor_name', models.CharField(max_length=100)),
                ('Patient_ID', models.IntegerField()),
                ('Doctor_ID', models.IntegerField()),
                ('Department', models.CharField(max_length=100)),
                ('Date_of_updation', models.DateField()),
                ('Diagnosis', models.TextField()),
                ('Diagnosis_description', models.TextField()),
                ('Doctor_advice', models.TextField()),
                ('Additional_comments', models.TextField()),
            ],
        ),
    ]
