# Generated by Django 3.1.7 on 2021-05-09 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0004_doctor_latest_diagnosis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor_latest_diagnosis',
            old_name='Additional_comments',
            new_name='additional_comments',
        ),
        migrations.RenameField(
            model_name='doctor_latest_diagnosis',
            old_name='Date_of_updation',
            new_name='date_of_updation',
        ),
        migrations.RenameField(
            model_name='doctor_latest_diagnosis',
            old_name='Department',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='doctor_latest_diagnosis',
            old_name='Diagnosis',
            new_name='diagnosis',
        ),
        migrations.RenameField(
            model_name='doctor_latest_diagnosis',
            old_name='Diagnosis_description',
            new_name='diagnosis_description',
        ),
        migrations.RenameField(
            model_name='doctor_latest_diagnosis',
            old_name='Doctor_ID',
            new_name='doctor_ID',
        ),
        migrations.RenameField(
            model_name='doctor_latest_diagnosis',
            old_name='Doctor_advice',
            new_name='doctor_advice',
        ),
        migrations.RenameField(
            model_name='doctor_latest_diagnosis',
            old_name='Doctor_name',
            new_name='doctor_name',
        ),
        migrations.RenameField(
            model_name='doctor_latest_diagnosis',
            old_name='Patient_ID',
            new_name='patient_ID',
        ),
        migrations.RenameField(
            model_name='doctor_latest_diagnosis',
            old_name='Patient_name',
            new_name='patient_name',
        ),
    ]
