# Generated by Django 3.1.7 on 2021-05-14 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0007_auto_20210512_1034'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor_latest_diagnosis',
        ),
    ]
