# Generated by Django 3.1.7 on 2021-05-14 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='become_member',
            name='Additional_comments',
        ),
    ]
